Add Debian 8 and Ubuntu 16.04 vagrant boxes
dfarrell07/vagrant-opendaylight pull request #31
Opened 2016-12-01 09:37 UTC by AkshitaJha

Signed-off-by: Akshita Jha <zenith158@gmail.com>

2016-12-01 21:16 UTC, dfarrell07 commented on Vagrantfile
> +    debian8_ansible.vm.box_version = "=8.5.2"
Maybe we should build it based on latest, so this doesn't need to be maintained to stay recent?

2016-12-01 21:17 UTC, dfarrell07 commented on Vagrantfile
> +      ansible.playbook = "provisioning/all_defaults_playbook.yml"
After you address https://github.com/dfarrell07/ansible-opendaylight/pull/28#pullrequestreview-11056029, you'll need to change this to define/use a playbook that sets deb_repo as install method.

2016-12-01 21:18 UTC, dfarrell07 commented on Vagrantfile
> +      ansible.playbook = "provisioning/all_defaults_playbook.yml"
Same deb_repo as install method feedback as above

2016-12-01 21:18 UTC, dfarrell07 commented on Vagrantfile
> +    ubuntu16_ansible.vm.box_version = "=20161130.0.0"
Same "maybe use latest?" feedback as above

2016-12-01 21:18 UTC, dfarrell07 requested changes
Looks great overall, thanks Akshita! Minor feedback inline.

2016-12-02 23:47 UTC, AkshitaJha commented on Vagrantfile
> +    debian8_ansible.vm.box_version = "=8.5.2"
Done.

2016-12-02 23:48 UTC, AkshitaJha commented on Vagrantfile
> +      ansible.playbook = "provisioning/all_defaults_playbook.yml"
I have added `provisioning/deb_path_install_playbook.yml` and `provisioning/deb_repo_install_playbook.yml`.

2016-12-05 21:17 UTC, dfarrell07 commented
Perfect Akshita, thanks! Statically reviewed and `vagrant up`'d/poked around, looks good.

2016-12-05 21:18 UTC, dfarrell07 approved these changes

2016-12-05 21:18 UTC, merged